package com.fulfai.partner;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

import com.fulfai.partner.branch.Branch;
import com.fulfai.partner.category.Category;
import com.fulfai.partner.company.Company;
import com.fulfai.partner.order.Order;
import com.fulfai.partner.order.OrderItem;
import com.fulfai.partner.product.Product;

import software.amazon.awssdk.enhanced.dynamodb.EnhancedType;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags;

public class Schemas {

    public static final TableSchema<Company> COMPANY_SCHEMA = TableSchema.builder(Company.class)
            .newItemSupplier(Company::new)
            .addAttribute(String.class, a -> a.name("id")
                    .getter(Company::getId)
                    .setter(Company::setId)
                    .tags(StaticAttributeTags.primaryPartitionKey()))
            .addAttribute(String.class, a -> a.name("name")
                    .getter(Company::getName)
                    .setter(Company::setName))
            .addAttribute(String.class, a -> a.name("address")
                    .getter(Company::getAddress)
                    .setter(Company::setAddress))
            .addAttribute(String.class, a -> a.name("city")
                    .getter(Company::getCity)
                    .setter(Company::setCity))
            .addAttribute(String.class, a -> a.name("country")
                    .getter(Company::getCountry)
                    .setter(Company::setCountry))
            .addAttribute(String.class, a -> a.name("email")
                    .getter(Company::getEmail)
                    .setter(Company::setEmail))
            .addAttribute(String.class, a -> a.name("licenseNo")
                    .getter(Company::getLicenseNo)
                    .setter(Company::setLicenseNo))
            .addAttribute(String.class, a -> a.name("logo")
                    .getter(Company::getLogo)
                    .setter(Company::setLogo))
            .addAttribute(String.class, a -> a.name("phoneNumber")
                    .getter(Company::getPhoneNumber)
                    .setter(Company::setPhoneNumber))
            .addAttribute(String.class, a -> a.name("trn")
                    .getter(Company::getTrn)
                    .setter(Company::setTrn))
            .addAttribute(String.class, a -> a.name("website")
                    .getter(Company::getWebsite)
                    .setter(Company::setWebsite))
            .addAttribute(EnhancedType.listOf(String.class), a -> a.name("operatingCountries")
                    .getter(Company::getOperatingCountries)
                    .setter(Company::setOperatingCountries))
            .addAttribute(Instant.class, a -> a.name("createdAt")
                    .getter(Company::getCreatedAt)
                    .setter(Company::setCreatedAt))
            .addAttribute(Instant.class, a -> a.name("updatedAt")
                    .getter(Company::getUpdatedAt)
                    .setter(Company::setUpdatedAt))
            .build();

    public static final TableSchema<Branch> BRANCH_SCHEMA = TableSchema.builder(Branch.class)
            .newItemSupplier(Branch::new)
            .addAttribute(String.class, a -> a.name("companyId")
                    .getter(Branch::getCompanyId)
                    .setter(Branch::setCompanyId)
                    .tags(StaticAttributeTags.primaryPartitionKey()))
            .addAttribute(String.class, a -> a.name("branchId")
                    .getter(Branch::getBranchId)
                    .setter(Branch::setBranchId)
                    .tags(StaticAttributeTags.primarySortKey()))
            .addAttribute(String.class, a -> a.name("name")
                    .getter(Branch::getName)
                    .setter(Branch::setName))
            .addAttribute(String.class, a -> a.name("address")
                    .getter(Branch::getAddress)
                    .setter(Branch::setAddress))
            .addAttribute(String.class, a -> a.name("city")
                    .getter(Branch::getCity)
                    .setter(Branch::setCity))
            .addAttribute(String.class, a -> a.name("country")
                    .getter(Branch::getCountry)
                    .setter(Branch::setCountry))
            .addAttribute(String.class, a -> a.name("phoneNumber")
                    .getter(Branch::getPhoneNumber)
                    .setter(Branch::setPhoneNumber))
            .addAttribute(String.class, a -> a.name("email")
                    .getter(Branch::getEmail)
                    .setter(Branch::setEmail))
            .addAttribute(String.class, a -> a.name("managerName")
                    .getter(Branch::getManagerName)
                    .setter(Branch::setManagerName))
            .addAttribute(Boolean.class, a -> a.name("isActive")
                    .getter(Branch::getIsActive)
                    .setter(Branch::setIsActive))
            .addAttribute(Instant.class, a -> a.name("createdAt")
                    .getter(Branch::getCreatedAt)
                    .setter(Branch::setCreatedAt))
            .addAttribute(Instant.class, a -> a.name("updatedAt")
                    .getter(Branch::getUpdatedAt)
                    .setter(Branch::setUpdatedAt))
            .build();

    public static final TableSchema<Category> CATEGORY_SCHEMA = TableSchema.builder(Category.class)
            .newItemSupplier(Category::new)
            .addAttribute(String.class, a -> a.name("companyId")
                    .getter(Category::getCompanyId)
                    .setter(Category::setCompanyId)
                    .tags(StaticAttributeTags.primaryPartitionKey()))
            .addAttribute(String.class, a -> a.name("name")
                    .getter(Category::getName)
                    .setter(Category::setName)
                    .tags(StaticAttributeTags.primarySortKey()))
            .addAttribute(String.class, a -> a.name("description")
                    .getter(Category::getDescription)
                    .setter(Category::setDescription))
            .addAttribute(String.class, a -> a.name("imageUrl")
                    .getter(Category::getImageUrl)
                    .setter(Category::setImageUrl))
            .addAttribute(Integer.class, a -> a.name("displayOrder")
                    .getter(Category::getDisplayOrder)
                    .setter(Category::setDisplayOrder))
            .addAttribute(Boolean.class, a -> a.name("isActive")
                    .getter(Category::getIsActive)
                    .setter(Category::setIsActive))
            .addAttribute(Instant.class, a -> a.name("createdAt")
                    .getter(Category::getCreatedAt)
                    .setter(Category::setCreatedAt))
            .addAttribute(Instant.class, a -> a.name("updatedAt")
                    .getter(Category::getUpdatedAt)
                    .setter(Category::setUpdatedAt))
            .build();

    public static final TableSchema<Product> PRODUCT_SCHEMA = TableSchema.builder(Product.class)
            .newItemSupplier(Product::new)
            .addAttribute(String.class, a -> a.name("companyId")
                    .getter(Product::getCompanyId)
                    .setter(Product::setCompanyId)
                    .tags(StaticAttributeTags.primaryPartitionKey(),
                            StaticAttributeTags.secondaryPartitionKey(Product.CATEGORY_GSI)))
            .addAttribute(String.class, a -> a.name("productId")
                    .getter(Product::getProductId)
                    .setter(Product::setProductId)
                    .tags(StaticAttributeTags.primarySortKey()))
            .addAttribute(String.class, a -> a.name("name")
                    .getter(Product::getName)
                    .setter(Product::setName))
            .addAttribute(String.class, a -> a.name("description")
                    .getter(Product::getDescription)
                    .setter(Product::setDescription))
            .addAttribute(String.class, a -> a.name("category")
                    .getter(Product::getCategory)
                    .setter(Product::setCategory)
                    .tags(StaticAttributeTags.secondarySortKey(Product.CATEGORY_GSI)))
            .addAttribute(String.class, a -> a.name("sku")
                    .getter(Product::getSku)
                    .setter(Product::setSku))
            .addAttribute(String.class, a -> a.name("barcode")
                    .getter(Product::getBarcode)
                    .setter(Product::setBarcode))
            .addAttribute(BigDecimal.class, a -> a.name("price")
                    .getter(Product::getPrice)
                    .setter(Product::setPrice))
            .addAttribute(BigDecimal.class, a -> a.name("costPrice")
                    .getter(Product::getCostPrice)
                    .setter(Product::setCostPrice))
            .addAttribute(String.class, a -> a.name("unit")
                    .getter(Product::getUnit)
                    .setter(Product::setUnit))
            .addAttribute(Integer.class, a -> a.name("stockQuantity")
                    .getter(Product::getStockQuantity)
                    .setter(Product::setStockQuantity))
            .addAttribute(Integer.class, a -> a.name("reorderLevel")
                    .getter(Product::getReorderLevel)
                    .setter(Product::setReorderLevel))
            .addAttribute(String.class, a -> a.name("imageUrl")
                    .getter(Product::getImageUrl)
                    .setter(Product::setImageUrl))
            .addAttribute(Boolean.class, a -> a.name("isActive")
                    .getter(Product::getIsActive)
                    .setter(Product::setIsActive))
            .addAttribute(Instant.class, a -> a.name("createdAt")
                    .getter(Product::getCreatedAt)
                    .setter(Product::setCreatedAt))
            .addAttribute(Instant.class, a -> a.name("updatedAt")
                    .getter(Product::getUpdatedAt)
                    .setter(Product::setUpdatedAt))
            .build();

    public static final TableSchema<OrderItem> ORDER_ITEM_SCHEMA = TableSchema.builder(OrderItem.class)
            .newItemSupplier(OrderItem::new)
            .addAttribute(String.class, a -> a.name("productId")
                    .getter(OrderItem::getProductId)
                    .setter(OrderItem::setProductId))
            .addAttribute(String.class, a -> a.name("productName")
                    .getter(OrderItem::getProductName)
                    .setter(OrderItem::setProductName))
            .addAttribute(String.class, a -> a.name("sku")
                    .getter(OrderItem::getSku)
                    .setter(OrderItem::setSku))
            .addAttribute(Integer.class, a -> a.name("quantity")
                    .getter(OrderItem::getQuantity)
                    .setter(OrderItem::setQuantity))
            .addAttribute(BigDecimal.class, a -> a.name("unitPrice")
                    .getter(OrderItem::getUnitPrice)
                    .setter(OrderItem::setUnitPrice))
            .addAttribute(BigDecimal.class, a -> a.name("totalPrice")
                    .getter(OrderItem::getTotalPrice)
                    .setter(OrderItem::setTotalPrice))
            .build();

    public static final TableSchema<Order> ORDER_SCHEMA = TableSchema.builder(Order.class)
            .newItemSupplier(Order::new)
            .addAttribute(String.class, a -> a.name("companyId")
                    .getter(Order::getCompanyId)
                    .setter(Order::setCompanyId)
                    .tags(StaticAttributeTags.primaryPartitionKey(),
                            StaticAttributeTags.secondaryPartitionKey(Order.DATE_STATUS_GSI)))
            .addAttribute(String.class, a -> a.name("orderId")
                    .getter(Order::getOrderId)
                    .setter(Order::setOrderId)
                    .tags(StaticAttributeTags.primarySortKey()))
            .addAttribute(Instant.class, a -> a.name("orderDate")
                    .getter(Order::getOrderDate)
                    .setter(Order::setOrderDate))
            .addAttribute(String.class, a -> a.name("status")
                    .getter(Order::getStatus)
                    .setter(Order::setStatus))
            .addAttribute(String.class, a -> a.name("dateStatusKey")
                    .getter(Order::getDateStatusKey)
                    .setter(Order::setDateStatusKey)
                    .tags(StaticAttributeTags.secondarySortKey(Order.DATE_STATUS_GSI)))
            .addAttribute(String.class, a -> a.name("branchId")
                    .getter(Order::getBranchId)
                    .setter(Order::setBranchId))
            .addAttribute(EnhancedType.listOf(EnhancedType.documentOf(OrderItem.class, ORDER_ITEM_SCHEMA)),
                    a -> a.name("items")
                            .getter(Order::getItems)
                            .setter(Order::setItems))
            .addAttribute(BigDecimal.class, a -> a.name("subtotal")
                    .getter(Order::getSubtotal)
                    .setter(Order::setSubtotal))
            .addAttribute(BigDecimal.class, a -> a.name("taxAmount")
                    .getter(Order::getTaxAmount)
                    .setter(Order::setTaxAmount))
            .addAttribute(BigDecimal.class, a -> a.name("discountAmount")
                    .getter(Order::getDiscountAmount)
                    .setter(Order::setDiscountAmount))
            .addAttribute(BigDecimal.class, a -> a.name("totalAmount")
                    .getter(Order::getTotalAmount)
                    .setter(Order::setTotalAmount))
            .addAttribute(String.class, a -> a.name("paymentMethod")
                    .getter(Order::getPaymentMethod)
                    .setter(Order::setPaymentMethod))
            .addAttribute(String.class, a -> a.name("paymentStatus")
                    .getter(Order::getPaymentStatus)
                    .setter(Order::setPaymentStatus))
            .addAttribute(String.class, a -> a.name("notes")
                    .getter(Order::getNotes)
                    .setter(Order::setNotes))
            .addAttribute(Instant.class, a -> a.name("createdAt")
                    .getter(Order::getCreatedAt)
                    .setter(Order::setCreatedAt))
            .addAttribute(Instant.class, a -> a.name("updatedAt")
                    .getter(Order::getUpdatedAt)
                    .setter(Order::setUpdatedAt))
            .build();
}
