package com.fulfai.deliverypartner;

import java.time.Instant;

import com.fulfai.deliverypartner.assignment.DriverOrderAssignment;
import com.fulfai.deliverypartner.company.Company;
import com.fulfai.deliverypartner.driver.Driver;
import com.fulfai.deliverypartner.location.DriverLocation;

import software.amazon.awssdk.enhanced.dynamodb.EnhancedType;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags;

public class Schemas {

        public static final TableSchema<Company> COMPANY_SCHEMA = TableSchema.builder(Company.class)
                        .newItemSupplier(Company::new)
                        .addAttribute(String.class, a -> a.name("id")
                                        .getter(Company::getId)
                                        .setter(Company::setId)
                                        .tags(StaticAttributeTags.primaryPartitionKey()))
                        .addAttribute(String.class, a -> a.name("name")
                                        .getter(Company::getName)
                                        .setter(Company::setName))
                        .addAttribute(String.class, a -> a.name("address")
                                        .getter(Company::getAddress)
                                        .setter(Company::setAddress))
                        .addAttribute(String.class, a -> a.name("city")
                                        .getter(Company::getCity)
                                        .setter(Company::setCity))
                        .addAttribute(String.class, a -> a.name("country")
                                        .getter(Company::getCountry)
                                        .setter(Company::setCountry))
                        .addAttribute(String.class, a -> a.name("email")
                                        .getter(Company::getEmail)
                                        .setter(Company::setEmail))
                        .addAttribute(String.class, a -> a.name("phoneNumber")
                                        .getter(Company::getPhoneNumber)
                                        .setter(Company::setPhoneNumber))
                        .addAttribute(String.class, a -> a.name("licenseNo")
                                        .getter(Company::getLicenseNo)
                                        .setter(Company::setLicenseNo))
                        .addAttribute(String.class, a -> a.name("logo")
                                        .getter(Company::getLogo)
                                        .setter(Company::setLogo))
                        .addAttribute(EnhancedType.listOf(String.class), a -> a.name("operatingCities")
                                        .getter(Company::getOperatingCities)
                                        .setter(Company::setOperatingCities))
                        .addAttribute(Boolean.class, a -> a.name("isActive")
                                        .getter(Company::getIsActive)
                                        .setter(Company::setIsActive))
                        .addAttribute(Instant.class, a -> a.name("createdAt")
                                        .getter(Company::getCreatedAt)
                                        .setter(Company::setCreatedAt))
                        .addAttribute(Instant.class, a -> a.name("updatedAt")
                                        .getter(Company::getUpdatedAt)
                                        .setter(Company::setUpdatedAt))
                        .build();

        public static final TableSchema<Driver> DRIVER_SCHEMA = TableSchema.builder(Driver.class)
                        .newItemSupplier(Driver::new)
                        .addAttribute(String.class, a -> a.name("companyId")
                                        .getter(Driver::getCompanyId)
                                        .setter(Driver::setCompanyId)
                                        .tags(StaticAttributeTags.primaryPartitionKey()))
                        .addAttribute(String.class, a -> a.name("driverId")
                                        .getter(Driver::getDriverId)
                                        .setter(Driver::setDriverId)
                                        .tags(StaticAttributeTags.primarySortKey()))
                        .addAttribute(String.class, a -> a.name("name")
                                        .getter(Driver::getName)
                                        .setter(Driver::setName))
                        .addAttribute(String.class, a -> a.name("phoneNumber")
                                        .getter(Driver::getPhoneNumber)
                                        .setter(Driver::setPhoneNumber))
                        .addAttribute(String.class, a -> a.name("email")
                                        .getter(Driver::getEmail)
                                        .setter(Driver::setEmail))
                        .addAttribute(String.class, a -> a.name("vehicleType")
                                        .getter(Driver::getVehicleType)
                                        .setter(Driver::setVehicleType))
                        .addAttribute(String.class, a -> a.name("vehicleNumber")
                                        .getter(Driver::getVehicleNumber)
                                        .setter(Driver::setVehicleNumber))
                        .addAttribute(String.class, a -> a.name("licenseNumber")
                                        .getter(Driver::getLicenseNumber)
                                        .setter(Driver::setLicenseNumber))
                        .addAttribute(String.class, a -> a.name("status")
                                        .getter(Driver::getStatus)
                                        .setter(Driver::setStatus)
                                        .tags(StaticAttributeTags.secondaryPartitionKey(Driver.STATUS_GSI)))
                        .addAttribute(String.class, a -> a.name("currentCity")
                                        .getter(Driver::getCurrentCity)
                                        .setter(Driver::setCurrentCity))
                        .addAttribute(Double.class, a -> a.name("lastLatitude")
                                        .getter(Driver::getLastLatitude)
                                        .setter(Driver::setLastLatitude))
                        .addAttribute(Double.class, a -> a.name("lastLongitude")
                                        .getter(Driver::getLastLongitude)
                                        .setter(Driver::setLastLongitude))
                        .addAttribute(Instant.class, a -> a.name("lastLocationUpdate")
                                        .getter(Driver::getLastLocationUpdate)
                                        .setter(Driver::setLastLocationUpdate))
                        .addAttribute(Boolean.class, a -> a.name("isActive")
                                        .getter(Driver::getIsActive)
                                        .setter(Driver::setIsActive))
                        .addAttribute(Instant.class, a -> a.name("createdAt")
                                        .getter(Driver::getCreatedAt)
                                        .setter(Driver::setCreatedAt))
                        .addAttribute(Instant.class, a -> a.name("updatedAt")
                                        .getter(Driver::getUpdatedAt)
                                        .setter(Driver::setUpdatedAt))
                        .build();

        public static final TableSchema<DriverOrderAssignment> ASSIGNMENT_SCHEMA = TableSchema
                        .builder(DriverOrderAssignment.class)
                        .newItemSupplier(DriverOrderAssignment::new)
                        .addAttribute(String.class, a -> a.name("driverId")
                                        .getter(DriverOrderAssignment::getDriverId)
                                        .setter(DriverOrderAssignment::setDriverId)
                                        .tags(StaticAttributeTags.primaryPartitionKey()))
                        .addAttribute(Instant.class, a -> a.name("assignedAt")
                                        .getter(DriverOrderAssignment::getAssignedAt)
                                        .setter(DriverOrderAssignment::setAssignedAt)
                                        .tags(StaticAttributeTags.primarySortKey()))
                        .addAttribute(String.class, a -> a.name("orderId")
                                        .getter(DriverOrderAssignment::getOrderId)
                                        .setter(DriverOrderAssignment::setOrderId)
                                        .tags(StaticAttributeTags
                                                        .secondaryPartitionKey(DriverOrderAssignment.ORDER_GSI)))
                        .addAttribute(String.class, a -> a.name("sellingPartnerId")
                                        .getter(DriverOrderAssignment::getSellingPartnerId)
                                        .setter(DriverOrderAssignment::setSellingPartnerId))
                        .addAttribute(String.class, a -> a.name("status")
                                        .getter(DriverOrderAssignment::getStatus)
                                        .setter(DriverOrderAssignment::setStatus)
                                        .tags(StaticAttributeTags
                                                        .secondaryPartitionKey(DriverOrderAssignment.STATUS_GSI)))
                        .addAttribute(String.class, a -> a.name("pickupAddress")
                                        .getter(DriverOrderAssignment::getPickupAddress)
                                        .setter(DriverOrderAssignment::setPickupAddress))
                        .addAttribute(Double.class, a -> a.name("pickupLatitude")
                                        .getter(DriverOrderAssignment::getPickupLatitude)
                                        .setter(DriverOrderAssignment::setPickupLatitude))
                        .addAttribute(Double.class, a -> a.name("pickupLongitude")
                                        .getter(DriverOrderAssignment::getPickupLongitude)
                                        .setter(DriverOrderAssignment::setPickupLongitude))
                        .addAttribute(String.class, a -> a.name("deliveryAddress")
                                        .getter(DriverOrderAssignment::getDeliveryAddress)
                                        .setter(DriverOrderAssignment::setDeliveryAddress))
                        .addAttribute(Double.class, a -> a.name("deliveryLatitude")
                                        .getter(DriverOrderAssignment::getDeliveryLatitude)
                                        .setter(DriverOrderAssignment::setDeliveryLatitude))
                        .addAttribute(Double.class, a -> a.name("deliveryLongitude")
                                        .getter(DriverOrderAssignment::getDeliveryLongitude)
                                        .setter(DriverOrderAssignment::setDeliveryLongitude))
                        .addAttribute(Instant.class, a -> a.name("pickedUpAt")
                                        .getter(DriverOrderAssignment::getPickedUpAt)
                                        .setter(DriverOrderAssignment::setPickedUpAt))
                        .addAttribute(Instant.class, a -> a.name("deliveredAt")
                                        .getter(DriverOrderAssignment::getDeliveredAt)
                                        .setter(DriverOrderAssignment::setDeliveredAt))
                        .addAttribute(String.class, a -> a.name("notes")
                                        .getter(DriverOrderAssignment::getNotes)
                                        .setter(DriverOrderAssignment::setNotes))
                        .addAttribute(Instant.class, a -> a.name("createdAt")
                                        .getter(DriverOrderAssignment::getCreatedAt)
                                        .setter(DriverOrderAssignment::setCreatedAt))
                        .addAttribute(Instant.class, a -> a.name("updatedAt")
                                        .getter(DriverOrderAssignment::getUpdatedAt)
                                        .setter(DriverOrderAssignment::setUpdatedAt))
                        .build();

        public static final TableSchema<DriverLocation> LOCATION_SCHEMA = TableSchema.builder(DriverLocation.class)
                        .newItemSupplier(DriverLocation::new)
                        .addAttribute(String.class, a -> a.name("driverId")
                                        .getter(DriverLocation::getDriverId)
                                        .setter(DriverLocation::setDriverId)
                                        .tags(StaticAttributeTags.primaryPartitionKey()))
                        .addAttribute(Instant.class, a -> a.name("timestamp")
                                        .getter(DriverLocation::getTimestamp)
                                        .setter(DriverLocation::setTimestamp)
                                        .tags(StaticAttributeTags.primarySortKey(),
                                                        StaticAttributeTags
                                                                        .secondarySortKey(DriverLocation.GEOHASH_GSI)))
                        .addAttribute(Double.class, a -> a.name("latitude")
                                        .getter(DriverLocation::getLatitude)
                                        .setter(DriverLocation::setLatitude))
                        .addAttribute(Double.class, a -> a.name("longitude")
                                        .getter(DriverLocation::getLongitude)
                                        .setter(DriverLocation::setLongitude))
                        .addAttribute(String.class, a -> a.name("geohash")
                                        .getter(DriverLocation::getGeohash)
                                        .setter(DriverLocation::setGeohash)
                                        .tags(StaticAttributeTags.secondaryPartitionKey(DriverLocation.GEOHASH_GSI)))
                        .addAttribute(Double.class, a -> a.name("accuracy")
                                        .getter(DriverLocation::getAccuracy)
                                        .setter(DriverLocation::setAccuracy))
                        .addAttribute(Double.class, a -> a.name("speed")
                                        .getter(DriverLocation::getSpeed)
                                        .setter(DriverLocation::setSpeed))
                        .addAttribute(Double.class, a -> a.name("heading")
                                        .getter(DriverLocation::getHeading)
                                        .setter(DriverLocation::setHeading))
                        .addAttribute(String.class, a -> a.name("status")
                                        .getter(DriverLocation::getStatus)
                                        .setter(DriverLocation::setStatus))
                        .build();
}
